### ISSUE TITLE
[Tutorial] fils.create_mask raises TypeError

### ISSUE THREAD

**Issue by bss9395** [e-koch/FilFinder#35]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-c685c54dec5f> in <module>()
----> 1 fils.create_mask(verbose=True)

D:\Anaconda3\envs\py2\lib\site-packages\fil_finder\filfind_class.pyc in create_mask(self, glob_thresh, adapt_thresh, smooth_size, size_thresh, verbose, test_mode, regrid, border_masking, zero_border, fill_hole_size, use_existing_mask, save_png)
    464 
    465         smooth_img = nd.median_filter(masking_img,
--> 466                                       size=round(self.smooth_size*ratio))
    467 
    468         # Set the border to zeros for the adaptive thresholding. Avoid border

D:\Anaconda3\envs\py2\lib\site-packages\scipy\ndimage\filters.pyc in median_filter(input, size, footprint, output, mode, cval, origin)
   1280     """
   1281     return _rank_filter(input, 0, size, footprint, output, mode, cval,
-> 1282                         origin, 'median')
   1283 
   1284 

D:\Anaconda3\envs\py2\lib\site-packages\scipy\ndimage\filters.pyc in _rank_filter(input, rank, size, footprint, output, mode, cval, origin, operation)
   1163             raise RuntimeError("no footprint or filter size provided")
   1164         sizes = _ni_support._normalize_sequence(size, input.ndim)
-> 1165         footprint = numpy.ones(sizes, dtype=bool)
   1166     else:
   1167         footprint = numpy.asarray(footprint, dtype=bool)

D:\Anaconda3\envs\py2\lib\site-packages\numpy\core\numeric.pyc in ones(shape, dtype, order)
    190 
    191     """
--> 192     a = empty(shape, dtype, order)
    193     multiarray.copyto(a, 1, casting='unsafe')
    194     return a

TypeError: 'float' object cannot be interpreted as an index

**Comment by e-koch** [comment]
Hi @bss9395 -- thanks for reporting the issue. I've released a new version with a fix for the issue.

`pip install fil_finder --upgrade` should install the new version 1.4.
