### ISSUE TITLE
Outdated version of FilFinder in PyPI

### ISSUE THREAD

**Issue by nbrucy** [e-koch/FilFinder#63]
Hello and thank you for this very useful piece of software.

I would just like to point out that the version available in [PyPI](https://pypi.org/project/FilFinder) is outdated (v1.2.2 from 2015) when it appears that the latest one on this repository is v1.7 . This may be confusing since both the README and the docs indicates pip as way to install FilFinder.

Best,

**Comment by e-koch** [comment]
Thanks, @nbrucy for pointing this out. Newer versions are available as `fil_finder`:
```pip install fil_finder ```

I'll remove this other version to avoid confusion in the future.

**Comment by nbrucy** [comment]
Ah yes this explains why it did not bump into this issue the first time I installed FilFinder.
Thank you very much !

**Comment by e-koch** [comment]
"FilFinder" is now removed on pypi.
