### ISSUE TITLE
Error in fil_finder setup command: use_2to3 is invalid

### ISSUE THREAD

**Issue by DavidLanders95** [e-koch/FilFinder#67]
This error appears when pip installing fil_finder into a new environment. Here is the full error log. 

Collecting fil-finder
  Using cached fil_finder-1.7.tar.gz (4.7 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/andy/miniconda3/envs/FibrilPicker/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7sno4lc_/fil-finder_1bd93f1d8a6440f4abb7329f6ade9000/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7sno4lc_/fil-finder_1bd93f1d8a6440f4abb7329f6ade9000/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xw__rmgz
       cwd: /tmp/pip-install-7sno4lc_/fil-finder_1bd93f1d8a6440f4abb7329f6ade9000/
  Complete output (1 lines):
  error in fil_finder setup command: use_2to3 is invalid.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2f/68/d0cafbbfb94a4c2a4b191762d7e0d2ffffe7671b3cb5792d6e924eb8ef11/fil_finder-1.7.tar.gz#sha256=8ec158f7c67c5b14a95ed8aeb5cfcb550421960ab4a9aeee21728339161a9391 (from https://pypi.org/simple/fil-finder/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached fil_finder-1.6.tar.gz (4.7 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/andy/miniconda3/envs/FibrilPicker/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7sno4lc_/fil-finder_7fb7b825bd3246188209bba85430ce11/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7sno4lc_/fil-finder_7fb7b825bd3246188209bba85430ce11/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_rgg_tnh
       cwd: /tmp/pip-install-7sno4lc_/fil-finder_7fb7b825bd3246188209bba85430ce11/
  Complete output (1 lines):
  error in fil_finder setup command: use_2to3 is invalid.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/4f/3d/2127a66a804ab8af777503f0a271ce61b4ea99ea9c623fb4fb42106701c5/fil_finder-1.6.tar.gz#sha256=84d74ef80d724bfd7d0517ae4d76f3e98eb6e592a64b0f1f3839a6033843c7aa (from https://pypi.org/simple/fil-finder/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached fil_finder-1.5.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/andy/miniconda3/envs/FibrilPicker/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7sno4lc_/fil-finder_ed1b46433eca4a70a824e8025263f7c4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7sno4lc_/fil-finder_ed1b46433eca4a70a824e8025263f7c4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zf8_1kbw
       cwd: /tmp/pip-install-7sno4lc_/fil-finder_ed1b46433eca4a70a824e8025263f7c4/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-7sno4lc_/fil-finder_ed1b46433eca4a70a824e8025263f7c4/setup.py", line 105, in <module>
      conf = config.ConfigParser()
  AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/31/1b/59cc606c8356c543019966f105ad86db8b55f53de1aea981f054776c73b5/fil_finder-1.5.tar.gz#sha256=885f23dbf2e2342ff453ea8bc1041f1e5781d46450db8635fdff6e1374df05b5 (from https://pypi.org/simple/fil-finder/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached fil_finder-1.4.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/andy/miniconda3/envs/FibrilPicker/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7sno4lc_/fil-finder_02f70a02fb45455cbb64ebeaf143557d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7sno4lc_/fil-finder_02f70a02fb45455cbb64ebeaf143557d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-a3gc_jus
       cwd: /tmp/pip-install-7sno4lc_/fil-finder_02f70a02fb45455cbb64ebeaf143557d/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-7sno4lc_/fil-finder_02f70a02fb45455cbb64ebeaf143557d/setup.py", line 105, in <module>
      conf = config.ConfigParser()
  AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b2/33/85ab5599d539d01a231ad17eb66f857f5fd023d198c1869450e0ca4028c9/fil_finder-1.4.tar.gz#sha256=b3007ff87b4bf446b27aa61b1c3bef6b8dcbf4267c034f6a10f8a0d9ec55b1b4 (from https://pypi.org/simple/fil-finder/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached fil_finder-1.3.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/andy/miniconda3/envs/FibrilPicker/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7sno4lc_/fil-finder_a07dd84e91b14de49caef55b7b44f5fa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7sno4lc_/fil-finder_a07dd84e91b14de49caef55b7b44f5fa/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-il7rhqpi
       cwd: /tmp/pip-install-7sno4lc_/fil-finder_a07dd84e91b14de49caef55b7b44f5fa/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-7sno4lc_/fil-finder_a07dd84e91b14de49caef55b7b44f5fa/setup.py", line 105, in <module>
      conf = config.ConfigParser()
  AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/db/b4/a0739e22bd23b4e8405efca8b414537144c5e0fc405243f897a581e9b0f9/fil_finder-1.3.tar.gz#sha256=6458d1f2d84b723dd96dc07843f8dd66e839ff0f6931312cc6f2b66b497dc1af (from https://pypi.org/simple/fil-finder/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement fil-finder (from versions: 1.3, 1.4, 1.5, 1.6, 1.7)
ERROR: No matching distribution found for fil-finder

**Comment by e-koch** [comment]
Thanks for reporting this, @DavidLanders95!

The problem was coming from not having a python 3.9 version. In case the install with the older setuptools version becomes an issue, running `pip install -U fil_finder` should install version 1.7.2 where this should now be fixed.
