### ISSUE TITLE
Use astropy.units 

### ISSUE THREAD

**Issue by e-koch** [e-koch/FilFinder#7]
Gracefully accept pixel and physical units for each parameter.

**Comment by e-koch** [comment]
Right now, physical results are either in pixel units (if no distance is given) or in parsecs by assumption.

**Comment by low-sky** [comment]
Integers for parameters should be interpreted as being in pixel units.  I.e., setting `smooth_size=7` should be interpreted as `smooth_size=7*u.pix`.

**Comment by e-koch** [comment]
Addressed in #41
