### ISSUE TITLE
Cannot show the skeleton and long path

### ISSUE THREAD

**Issue by mikami520** [e-koch/FilFinder#72]
Hi, I am working on a skeleton of 3D mesh. I saved the trimesh.path3D to trimesh.path2D as a ```dxf``` file. Then I used online convertor to convert ```dxf``` to ```png```. Next, I used the fil_finder to find the largest path. However, when I plot the final result, it is all black without any path or original skeleton. Could someone help me solve this issue? I attached the source image file to this issue.
```
import numpy as np
import cv2
import matplotlib.pyplot as plt
from fil_finder import FilFinder2D
import astropy.units as u

skeleton = cv2.imread("/Users/mikamixiao/Desktop/test.png", 0) #in numpy array format
fil = FilFinder2D(skeleton, distance=250 * u.pc, mask=skeleton)
fil.preprocess_image(flatten_percent=85)
fil.create_mask(border_masking=True, verbose=False,
use_existing_mask=True)
fil.medskel(verbose=False)
plt.imshow(fil.skeleton, cmap='gray', origin='lower')
fil.analyze_skeletons(branch_thresh=40 * u.pix, prune_criteria='length', skel_thresh=10*u.pix)

# Show the longest path
plt.imshow(fil.skeleton, cmap='gray', origin='lower')
plt.contour(fil.skeleton_longpath, colors='r')
plt.axis('off')
plt.show()
```
Here is the result I get from above code:
![Screen Shot 2022-04-01 at 20 12 15](https://user-images.githubusercontent.com/70731556/161356137-8204657d-88c0-4cd1-add8-42959557b87e.png)

By the way, is there anyway to do the branch pruning on 3D path instead of a 2D png image?

[test.png.zip](https://github.com/e-koch/FilFinder/files/8401391/test.png.zip)

**Comment by e-koch** [comment]
Hi @mikami520 -- apologies the slow reply.

I think it's the dtype of the input skeleton that caused this issue as its expecting a boolean mask input. The `fil.preprocess_image` will have issues interpreting a boolean image, but can be skipped with `skip_flatten=True`:

```
skeleton = cv2.imread("/Users/mikamixiao/Desktop/test.png", 0) #in numpy array format
fil = FilFinder2D(skeleton, distance=250 * u.pc, mask=skeleton)
fil.preprocess_image(skip_flatten=True)
fil.create_mask(border_masking=True, verbose=False,
use_existing_mask=True)
fil.medskel(verbose=False)
plt.imshow(fil.skeleton, cmap='gray', origin='lower')
fil.analyze_skeletons(branch_thresh=40 * u.pix, prune_criteria='length', skel_thresh=10*u.pix)

# Show the longest path
plt.imshow(fil.skeleton, cmap='gray', origin='lower')
plt.contour(fil.skeleton_longpath, colors='r')
plt.axis('off')
plt.show()
```

Here's what I get from the test image:
![image](https://user-images.githubusercontent.com/3255771/162589684-1a0a61fc-6604-4b73-be58-f936146facee.png)

**Comment by mikami520** [comment]
> Hi @mikami520 -- apologies the slow reply.
> 
> I think it's the dtype of the input skeleton that caused this issue as its expecting a boolean mask input. The `fil.preprocess_image` will have issues interpreting a boolean image, but can be skipped with `skip_flatten=True`:
> 
> ```
> skeleton = cv2.imread("/Users/mikamixiao/Desktop/test.png", 0) #in numpy array format
> fil = FilFinder2D(skeleton, distance=250 * u.pc, mask=skeleton)
> fil.preprocess_image(skip_flatten=True)
> fil.create_mask(border_masking=True, verbose=False,
> use_existing_mask=True)
> fil.medskel(verbose=False)
> plt.imshow(fil.skeleton, cmap='gray', origin='lower')
> fil.analyze_skeletons(branch_thresh=40 * u.pix, prune_criteria='length', skel_thresh=10*u.pix)
> 
> # Show the longest path
> plt.imshow(fil.skeleton, cmap='gray', origin='lower')
> plt.contour(fil.skeleton_longpath, colors='r')
> plt.axis('off')
> plt.show()
> ```
> 
> Here's what I get from the test image: ![image](https://user-images.githubusercontent.com/3255771/162589684-1a0a61fc-6604-4b73-be58-f936146facee.png)

@e-koch Thanks for your help. That solved my issues. Thanks again!
