### ISSUE TITLE
fil.create_mask(verbose=True, border_masking=False)

### ISSUE THREAD

**Issue by ven1996** [e-koch/FilFinder#74]
0
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-23-d322482ee290> in <module>
----> 1 fil.create_mask(verbose=True, border_masking=False)

~/.local/lib/python3.8/site-packages/fil_finder/filfinder2D.py in create_mask(self, glob_thresh, adapt_thresh, smooth_size, size_thresh, verbose, test_mode, regrid, border_masking, border_kwargs, fill_hole_size, use_existing_mask, save_png)
    402 
    403         med_filter_size = int(round(self.smooth_size.value * ratio))
--> 404         smooth_img = nd.median_filter(masking_img,
    405                                       size=med_filter_size)
    406 

~/.local/lib/python3.8/site-packages/scipy/ndimage/_filters.py in median_filter(input, size, footprint, output, mode, cval, origin)
   1394     >>> plt.show()
   1395     """
-> 1396     return _rank_filter(input, 0, size, footprint, output, mode, cval,
   1397                         origin, 'median')
   1398 

~/.local/lib/python3.8/site-packages/scipy/ndimage/_filters.py in _rank_filter(input, rank, size, footprint, output, mode, cval, origin, operation)
   1260     print(len(fshape))
   1261     if len(fshape) != input.ndim:
-> 1262         raise RuntimeError('filter footprint array has incorrect shape.')
   1263     for origin, lenf in zip(origins, fshape):
   1264         if (lenf // 2 + origin < 0) or (lenf // 2 + origin >= lenf):

RuntimeError: filter footprint array has incorrect shape.

**Comment by Scattered1234** [comment]
Hello, I am also having this issue, have you solved it? Could you tell me how you solved this issue?
