### ISSUE TITLE
Problem with FilFinder2D import

### ISSUE THREAD

**Issue by AgnieszkaP23** [e-koch/FilFinder#87]
I have wanted to use FilFinder 2D in my research (similar problem as described here: https://stackoverflow.com/questions/33979742/ideas-how-to-measure-the-length-of-a-skeleton-using-python). Until 2-3 months ago everything worked fine, but now I have a problem with importing FilFinder2D and this is regardless of the fil_finder version.... Is it possible to solve this somehow?
<img width="1871" alt="ImportError" src="https://github.com/user-attachments/assets/cba89717-210d-44c3-a8db-0615b97d456f">

**Comment by e-koch** [comment]
Hi @AgnieszkaP23  -- please install from the master branch of the repo. The problem is fixed there but I haven't pushed a new release to pypi.
